# Generated by Django 3.0.3 on 2020-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
    ]
